name: Build and deploy ASP.Net Core app to Azure Web App - Ninety

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ./publish

      - name: Upload published app for deployment
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app

      - name: Login to Azure 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A259929115F4AB682DEAB3CA73B6C96 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6CF8C278DDA472CA68248217ECFC365 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A53B78D5AF6C430DBE2248803239658E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Ninety'
          slot-name: 'Production'
          package: ./publish
    